{
  "id": "try-catch",
  "name": "Try/Catch",
  "index": 17,
  "lesson": 17,
  "summary": "Introduction to Try/Catch and how to use it in your smart contracts.",
  "labels": [
    "solidity"
  ],
  "content": {
    "compiledSource": "/*@jsxRuntime automatic @jsxImportSource react*/\nconst {Fragment: _Fragment, jsxDEV: _jsxDEV} = arguments[0];\nconst {useMDXComponents: _provideComponents} = arguments[0];\nfunction _createMdxContent(props) {\n  const _components = Object.assign({\n    h1: \"h1\",\n    p: \"p\",\n    code: \"code\",\n    ul: \"ul\",\n    li: \"li\",\n    pre: \"pre\"\n  }, _provideComponents(), props.components);\n  return _jsxDEV(_Fragment, {\n    children: [_jsxDEV(_components.h1, {\n      children: \"Try/Catch\"\n    }, undefined, false, {\n      fileName: \"<source.js>\",\n      lineNumber: 2,\n      columnNumber: 1\n    }, this), \"\\n\", _jsxDEV(_components.p, {\n      children: \"A failure in an external call can be gracefully caught using a try/catch statement.\"\n    }, undefined, false, {\n      fileName: \"<source.js>\",\n      lineNumber: 4,\n      columnNumber: 1\n    }, this), \"\\n\", _jsxDEV(_components.p, {\n      children: [\"The \", _jsxDEV(_components.code, {\n        children: \"try\"\n      }, undefined, false, {\n        fileName: \"<source.js>\",\n        lineNumber: 6,\n        columnNumber: 5\n      }, this), \" keyword has to be followed by an external function call.\"]\n    }, undefined, true, {\n      fileName: \"<source.js>\",\n      lineNumber: 6,\n      columnNumber: 1\n    }, this), \"\\n\", _jsxDEV(_components.p, {\n      children: [\"Solidity also supports various \", _jsxDEV(_components.code, {\n        children: \"catch\"\n      }, undefined, false, {\n        fileName: \"<source.js>\",\n        lineNumber: 8,\n        columnNumber: 32\n      }, this), \" blocks to handle different types of exceptions:\"]\n    }, undefined, true, {\n      fileName: \"<source.js>\",\n      lineNumber: 8,\n      columnNumber: 1\n    }, this), \"\\n\", _jsxDEV(_components.ul, {\n      children: [\"\\n\", _jsxDEV(_components.li, {\n        children: [_jsxDEV(_components.code, {\n          children: \"catch Error(string memory reason)\"\n        }, undefined, false, {\n          fileName: \"<source.js>\",\n          lineNumber: 10,\n          columnNumber: 3\n        }, this), \" to catch failing \", _jsxDEV(_components.code, {\n          children: \"revert()\"\n        }, undefined, false, {\n          fileName: \"<source.js>\",\n          lineNumber: 10,\n          columnNumber: 56\n        }, this), \" and \", _jsxDEV(_components.code, {\n          children: \"require()\"\n        }, undefined, false, {\n          fileName: \"<source.js>\",\n          lineNumber: 10,\n          columnNumber: 71\n        }, this)]\n      }, undefined, true, {\n        fileName: \"<source.js>\",\n        lineNumber: 10,\n        columnNumber: 1\n      }, this), \"\\n\", _jsxDEV(_components.li, {\n        children: [_jsxDEV(_components.code, {\n          children: \"catch Panic(uint256 panicCode){...}\"\n        }, undefined, false, {\n          fileName: \"<source.js>\",\n          lineNumber: 11,\n          columnNumber: 3\n        }, this), \" to catch failing panic error, i.e. failing \", _jsxDEV(_components.code, {\n          children: \"assert\"\n        }, undefined, false, {\n          fileName: \"<source.js>\",\n          lineNumber: 11,\n          columnNumber: 84\n        }, this), \"(), division by zero, arithmetic overflow, etc.\"]\n      }, undefined, true, {\n        fileName: \"<source.js>\",\n        lineNumber: 11,\n        columnNumber: 1\n      }, this), \"\\n\", _jsxDEV(_components.li, {\n        children: [_jsxDEV(_components.code, {\n          children: \"catch (bytes memory reason){...}\"\n        }, undefined, false, {\n          fileName: \"<source.js>\",\n          lineNumber: 12,\n          columnNumber: 3\n        }, this), \" to catch error signatures which does not match any other clause. In result, the declared variable returns the low-level error data.\"]\n      }, undefined, true, {\n        fileName: \"<source.js>\",\n        lineNumber: 12,\n        columnNumber: 1\n      }, this), \"\\n\", _jsxDEV(_components.li, {\n        children: [_jsxDEV(_components.code, {\n          children: \"catch {...}\"\n        }, undefined, false, {\n          fileName: \"<source.js>\",\n          lineNumber: 13,\n          columnNumber: 3\n        }, this), \" can be used if you are not interested in the error data.\"]\n      }, undefined, true, {\n        fileName: \"<source.js>\",\n        lineNumber: 13,\n        columnNumber: 1\n      }, this), \"\\n\"]\n    }, undefined, true, {\n      fileName: \"<source.js>\",\n      lineNumber: 10,\n      columnNumber: 1\n    }, this), \"\\n\", _jsxDEV(_components.pre, {\n      children: _jsxDEV(_components.code, {\n        className: \"language-solidity\",\n        children: \"// SPDX-License-Identifier: MIT\\npragma solidity ^0.8.24;\\n\\n// External contract used for try / catch examples\\ncontract ExternalContract {\\n    address public owner;\\n\\n    constructor(address _owner) {\\n        require(_owner != address(0), \\\"Invalid address\\\");\\n        assert(_owner != 0x0000000000000000000000000000000000000001);\\n        owner = _owner;\\n    }\\n\\n    function performAction(uint256 x) public pure returns (string memory) {\\n        require(x != 0, \\\"Require failed\\\");\\n        return \\\"Action performed\\\";\\n    }\\n}\\n\\ncontract MainContract {\\n    event Log(string message);\\n    event LogBytes(bytes data);\\n\\n    ExternalContract public externalContract;\\n\\n    constructor() {\\n        // This ExternalContract is used for example of try catch with external call\\n        externalContract = new ExternalContract(msg.sender);\\n    }\\n\\n    // Example of try / catch with external call\\n    // handleExternalCall(0) => Log(\\\"External call failed\\\")\\n    // handleExternalCall(1) => Log(\\\"Action performed\\\")\\n    function handleExternalCall(uint256 _i) public {\\n        try externalContract.performAction(_i) returns (string memory result) {\\n            emit Log(result);\\n        } catch {\\n            emit Log(\\\"External call failed\\\");\\n        }\\n    }\\n\\n    // Example of try / catch with contract creation\\n    // handleNewContract(0x0000000000000000000000000000000000000000) => Log(\\\"Invalid address\\\")\\n    // handleNewContract(0x0000000000000000000000000000000000000001) => LogBytes(\\\"\\\")\\n    // handleNewContract(0x0000000000000000000000000000000000000002) => Log(\\\"ExternalContract created\\\")\\n    function handleNewContract(address _owner) public {\\n        try new ExternalContract(_owner) returns (ExternalContract _externalContract) {\\n            // you can use variable _externalContract here\\n            emit Log(\\\"ExternalContract created\\\");\\n        } catch Error(string memory reason) {\\n            // catch failing revert() and require()\\n            emit Log(reason);\\n        } catch (bytes memory reason) {\\n            // catch failing assert()\\n            emit LogBytes(reason);\\n        }\\n    }\\n}\\n\"\n      }, undefined, false, {\n        fileName: \"<source.js>\",\n        lineNumber: 15,\n        columnNumber: 1\n      }, this)\n    }, undefined, false, {\n      fileName: \"<source.js>\",\n      lineNumber: 15,\n      columnNumber: 1\n    }, this)]\n  }, undefined, true, {\n    fileName: \"<source.js>\",\n    lineNumber: 1,\n    columnNumber: 1\n  }, this);\n}\nfunction MDXContent(props = {}) {\n  const {wrapper: MDXLayout} = Object.assign({}, _provideComponents(), props.components);\n  return MDXLayout ? _jsxDEV(MDXLayout, Object.assign({}, props, {\n    children: _jsxDEV(_createMdxContent, props, undefined, false, {\n      fileName: \"<source.js>\"\n    }, this)\n  }), undefined, false, {\n    fileName: \"<source.js>\"\n  }, this) : _createMdxContent(props);\n}\nreturn {\n  default: MDXContent\n};\n",
    "frontmatter": {},
    "scope": {}
  }
}